/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations.index'
import { Route as PresentationsIdIndexRouteImport } from './routes/presentations.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/presentations/',
  path: '/presentations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIdIndexRoute = PresentationsIdIndexRouteImport.update({
  id: '/presentations/$id/',
  path: '/presentations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/presentations/$id/': typeof PresentationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsIndexRoute
  '/presentations/$id': typeof PresentationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/presentations/$id/': typeof PresentationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/presentations/' | '/presentations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/presentations' | '/presentations/$id'
  id: '__root__' | '/' | '/presentations/' | '/presentations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
  PresentationsIdIndexRoute: typeof PresentationsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/presentations'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/$id/': {
      id: '/presentations/$id/'
      path: '/presentations/$id'
      fullPath: '/presentations/$id/'
      preLoaderRoute: typeof PresentationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
  PresentationsIdIndexRoute: PresentationsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
